language: c
compiler:
  - clang
  - gcc

env:
  - TOXENV=py26,coveralls
  - TOXENV=py27,coveralls
  - TOXENV=py32,coveralls
  - TOXENV=py33,coveralls
  - TOXENV=py34,coveralls
  - TOXENV=gcovr,cpp-coveralls

matrix:
  exclude:
    - compiler: gcc
      env: TOXENV=gcovr,cpp-coveralls

before_install:
  - "sudo add-apt-repository --yes ppa:kalakris/cmake"
  - "sudo apt-get update"
  - "sudo apt-get install cmake"
install:
  - "pip install --user tox"
script:
  - "$HOME/.local/bin/tox -- -rs"
