language: python


matrix:
  include:

    - python: 2.6
      env: TOXENV=py26,coveralls _COMPILER=clang

    - python: 2.7
      env: TOXENV=py27,coveralls _COMPILER=clang

    - python: 3.3
      env: TOXENV=py33,coveralls _COMPILER=clang

    - python: 3.4
      env: TOXENV=py34,coveralls _COMPILER=clang

    - python: 3.5
      env: TOXENV=py35,coveralls _COMPILER=clang

    - python: 2.6
      env: TOXENV=py26,coveralls _COMPILER=gcc

    - python: 2.7
      env: TOXENV=py27,coveralls _COMPILER=gcc

    - python: 3.3
      env: TOXENV=py33,coveralls _COMPILER=gcc

    - python: 3.4
      env: TOXENV=py34,coveralls _COMPILER=gcc

    - python: 3.5
      env: TOXENV=py35,coveralls _COMPILER=gcc


before_install:
  - "sudo add-apt-repository --yes ppa:kalakris/cmake"
  - "sudo apt-get update"
  - "sudo apt-get install cmake"
  - "curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- - --yes --verbose --channel=nightly"
  - "source .travis/setup.sh"
install:
  - "pip install tox"
script:
  - "tox -- -rs"
