language: python


matrix:
  include:

    - python: 2.6
      env: TOXENV=py26,coveralls CC=clang

    - python: 2.7
      env: TOXENV=py27,coveralls CC=clang

    - python: 3.2
      env: TOXENV=py32,coveralls CC=clang

    - python: 3.3
      env: TOXENV=py33,coveralls CC=clang

    - python: 3.4
      env: TOXENV=py34,coveralls CC=clang

    - python: 2.6
      env: TOXENV=py26,coveralls CC=gcc

    - python: 2.7
      env: TOXENV=py27,coveralls CC=gcc

    - python: 3.2
      env: TOXENV=py32,coveralls CC=gcc

    - python: 3.3
      env: TOXENV=py33,coveralls CC=gcc

    - python: 3.4
      env: TOXENV=py34,coveralls CC=gcc

    - python: 2.7
      env: TOXENV=gcovr,cpp-coveralls CC=clang


before_install:
  - "sudo add-apt-repository --yes ppa:kalakris/cmake"
  - "sudo apt-get update"
  - "sudo apt-get install cmake"
install:
  - "pip install --user tox"
script:
  - "$HOME/.local/bin/tox -- -rs"
