language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

install:
  # duplicated because pip can't do `install .` with variants
  - "pip install pytest pyyaml cykeccak coveralls --use-mirrors"
  - "bash .travis.install"
  # to get vcversioner to generate _version.py
  - "python setup.py build"
script: "py.test passacre"
after_success: "coveralls"
