sudo: required
dist: trusty
language: python


matrix:
  include:

    - python: 2.6
      env: TOXENV=py26 _COMPILER=clang

    - python: 2.7
      env: TOXENV=py27 _COMPILER=clang

    - python: 3.3
      env: TOXENV=py33 _COMPILER=clang

    - python: 3.4
      env: TOXENV=py34 _COMPILER=clang

    - python: 3.5
      env: TOXENV=py35 _COMPILER=clang

    - python: 2.6
      env: TOXENV=py26 _COMPILER=gcc

    - python: 2.7
      env: TOXENV=py27 _COMPILER=gcc

    - python: 3.3
      env: TOXENV=py33 _COMPILER=gcc

    - python: 3.4
      env: TOXENV=py34 _COMPILER=gcc

    - python: 3.5
      env: TOXENV=py35 _COMPILER=gcc

    - python: 2.7
      env: TOXENV=kcov _COMPILER=clang _KCOV=1

    - rust: nightly
      env: TOXENV=rust _COMPILER=clang _KCOV=1


before_install:
  - "sudo apt-get update"
  - "curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- - --yes --verbose --channel=nightly"
  - "source .travis/setup.sh"
install:
  - "pip install tox"
script:
  - "tox -- -rs"
after_success:
  - "tox -e codecov"
